# Site settings
title: Iotos Blog
email: contato@iotos.com.br
description: Iotos Blog
baseurl: "/blog"
url: "https://nutriotos.github.io/"
twitter_username: iotos_sistemas
github_username: iotos

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/styles
