# Site settings
title: Iotos Blog
email: your-email@domain.com
description: Iotos Blog
baseurl: "/blog"
url: "https://nutriotos.github.io/"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/styles
